id: A1E581785
base_file: fA777.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:50:32.387795
  last_modified_at: 2022-05-30 22:50:32.387805
